CREATE DATABASE IF NOT EXISTS userServiceDB;
CREATE DATABASE IF NOT EXISTS authServiceDB;
CREATE DATABASE IF NOT EXISTS expenseServiceDB;

CREATE USER IF NOT EXISTS 'root'@'%'
IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON userServiceDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON authServiceDB.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON expenseServiceDB.* TO 'root'@'%';

FLUSH PRIVILEGES;